#!/bin/bash

# Convenience variable to the cred path
CREDENTIALS="${AWS_PATH}/credentials/trike"

# No CloudFormation (perhaps)
unset AWS_CREDENTIAL_FILE

export AWS_ACCESS_KEY_ID="aws_access_key_id"
export AWS_SECRET_ACCESS_KEY="aws_secret_access_key"
export EC2_PRIVATE_KEY="${CREDENTIALS}/pk.pem"
export EC2_CERT="${CREDENTIALS}/cert.pem"
