set nocompatible      " We're running Vim, not Vi

let $PATH = '~/bin:/usr/local/bin:/usr/local/sbin:' . $PATH

set encoding=utf8 nobomb " BOM often causes trouble
if &t_Co > 1
  syntax enable       " Enable syntax highlighting without clobbering colors
endif
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugin
behave xterm
set visualbell        " must turn visual bell on to remove audio bell
set linebreak                 " when wrapping, try to break at characters in breakat
set breakat=\ ^I!@*-+;:,./?   " when wrapping, break at these characters
set showbreak=>               " character to show that a line is wrapped
set ignorecase    " ignore case when searching
set smartcase     " override ignorecase when there are uppercase characters
set showmatch     " when inserting a bracket briefly flash its match
set modeline
set number        " display line numbers
set mouse=a
set history=500
set showcmd
set title
set scrolloff=5
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
colorscheme desert
set incsearch
set hlsearch
nmap <silent> <leader>n :silent :nohlsearch<CR>
set shortmess=atI

set signcolumn=yes   " persistent sign column

set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set laststatus=2
set expandtab
set smarttab
autocmd FileType make     set noexpandtab
if !has('nvim')
  set cm=blowfish  " when encrypting files with :X, use blowfish instead of hopelessly insecure zip
endif
set ruler
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P>

" Setup automatic text formatting/wrapping:
set formatoptions=
set formatoptions-=t " Don't autowrap text
set formatoptions+=c " Do autowrap comments
set formatoptions+=r " Automatically continue comments
set formatoptions+=o " Automatically continue comments when hitting 'o' or 'O'
set formatoptions+=q " Allow formatting of comments with 'gq'
set formatoptions+=n " Recognize numbered lists
set formatoptions+=l " Don't break long lines that were already there

" Make window splitting behave
set noequalalways
set splitbelow

set backspace=eol,start,indent " make backspace work
"set hidden " no need to save to change buffers
" shellslash (use a common path separator across all platforms)
" convert all backslashes to forward slashes on expanding filenames.
" Enables consistancy in Cream between Windows and Linux platforms,
" but BE CAREFUL! Windows file operations require backslashes--any
" paths determined manually (not by Vim) need to be reversed.
set shellslash
" By default, pressing <TAB> in command mode will choose the first possible
" completion with no indication of how many others there might be. The following
" configuration lets you see what your other options are
set wildmenu
set wildmode=list:longest

" Search for ctags from current dir up to root
" set tags=./tags;
"   disabled - easytags uses ~/.vimtags


" Restore cursor position
autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif

" lcd to directory of file on entering buffer
autocmd BufEnter * silent! lcd %:p:h

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup
au BufWrite /private/tmp/crontab.* set nobackup

" Reload this vimrc when it changes  TODO: fix this
augroup myvimrc
  if has('nvim')
    let expanded_vimrc = resolve(expand($MYVIMRC)) . ',' . resolve(expand('~/.vim/vimrc'))
    let expanded_gvimrc = resolve(expand($MYGVIMRC)) . ',' . resolve(expand('~/.vim/vimrc'))
  else
    let expanded_vimrc = resolve(expand($MYVIMRC))
    let expanded_gvimrc = resolve(expand($MYGVIMRC))
  endif
  autocmd!
  execute 'autocmd! BufWritePost $MYVIMRC,' . expanded_vimrc . ' tabdo windo source $MYVIMRC | filetype detect | redraw'
  execute 'autocmd! BufWritePost $MYGVIMRC,' . expanded_gvimrc . ' if has("gui_running") | tabdo windo so $MYGVIMRC | filetype detect | redraw | endif'
augroup END


" Mappings
" ########
let mapleader = ","   " <leader> now means ',' rather than '\'

" <C-e> and <C-y> scroll the viewport a single line
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Substitute the word under the cursor
nnoremap <Leader>s :%s/\C\<<C-r><C-w>\>//gc<Left><Left><Left>
vnoremap <Leader>s y:%s/\C\<<C-r>"\>//gc<Left><Left><Left>

" Make moving around in Command-mode less painful
cnoremap <C-A> <Home>
cnoremap <C-E> <End>

" ## Input mappings
" New line below, above  TODO: fix this in nvim
inoremap <S-CR> <ESC>o
inoremap <C-CR> <ESC><S-o>

" Forward delete in insert mode
inoremap <C-d> <Delete>

" Refactoring: rename local variable
"   gd - jump to definition of word under cursor
"   [{ - jump to start of block
"   V  - visual block mode
"   %  - jump to end of block
"   :  - command mode
"   s/ - substitude 
"   <C-R>/ - insert text of last search
"   //gd<left><left><left> - finish subtitute command and move cursor
nmap gr gd[{V%:s/<C-R>///gc<left><left><left>
" Refactoring: rename variable across whole file
"   [{ - jump to start of block
"   V  - visual block mode
"   %  - jump to end of block
"   :  - command mode
"   s/ - substitude 
"   <C-R>/ - insert text of last search
"   //gd<left><left><left> - finish subtitute command and move cursor
nnoremap gR gD:%s/<C-R>///gc<left><left><left>

" Plugins
" #######

" vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/bundle')
Plug 'junegunn/vim-plug'  " to enable help for vim-plug itself
Plug 'neomake/neomake' " Async make (linters, syntax checke)
" Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' } " File explorer
" Plug 'wellle/targets.vim'
" Plug 'inkarkat/vim-SyntaxRange' " (lots of potential, but doesn't work reliably)
Plug 'xolox/vim-misc'     " req for: xolox/vim-easytags
Plug 'xolox/vim-easytags'
Plug 'rizzatti/dash.vim'  " Dash.app integration
Plug 'vim-airline/vim-airline'  " vim modeline decorations

" input
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary' " Comment toggle
Plug 'tpope/vim-repeat' " Make plugin commands repeatable with .
Plug 'tpope/vim-endwise' " Auto close if, do, def, etc.
Plug 'tpope/vim-surround' " Easily delete, change and add surroundings in pairs

" linting
Plug 'scrooloose/syntastic' " Syntastic: Code linting errors

" commands
Plug 'tpope/vim-eunuch' " Unix shell commands that act on the file and the buffer simultaneously
" TODO: ?? search dups ??
Plug '/usr/local/opt/fzf' " req for: junegunn/fzf
Plug 'junegunn/fzf.vim'   " fzf fuzzy finder
Plug 'ctrlpvim/ctrlp.vim'
" Plug 'mileszs/ack.vim' " File search with ack

" vim-plug filetypes
Plug 'sheerun/vim-polyglot'   " TODO: check which below are included
Plug 'tpope/vim-git', { 'for': 'git' }
Plug 'vim-ruby/vim-ruby', { 'for': 'ruby' }
Plug 'tpope/vim-rails', { 'for': 'ruby' }
Plug 'ecomba/vim-ruby-refactoring', { 'for': 'ruby' }
Plug 'jgdavey/vim-blockle', { 'for': 'ruby' } " <leader>b to toggle Ruby block style
Plug 'tpope/vim-rake', { 'for': 'ruby' }
Plug 'tpope/vim-bundler', { 'for': 'ruby' }
Plug 'plasticboy/vim-markdown', { 'for': 'markdown' }
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'vim-scripts/vim-coffee-script', { 'for': 'coffee' }
Plug 'dag/vim-fish', { 'for': 'fish' }
Plug 'thalesmello/lkml.vim', { 'for': 'lkml' }
Plug 'rodjek/vim-puppet', { 'for': 'puppet' }
Plug 'tbastos/vim-lua', { 'for': 'lua' } " syntax highlighting only
Plug 'xolox/vim-lua-ftplugin', { 'for': 'lua' }
Plug 'ElmCast/elm-vim'
Plug 'ndmitchell/ghcid', { 'rtp': 'plugins/nvim' }
Plug 'leafo/moonscript-vim'
Plug 'tyru/open-browser.vim'
Plug 'aklt/plantuml-syntax'            , { 'for': 'plantuml' } " plantuml UML tool
call plug#end()

" vim-easytags plugin
let g:easytags_async=1

" dash.vim plugin
nmap <silent> <leader>d <Plug>DashSearch

" rails.vim plugin
let g:rails_level=4
let g:rails_subversion=1
" /rails.vim

" NERDTree plugin
let NERDTreeIgnore=['\~$', '^\.git', '\.swp$', '\.DS_Store$']
let NERDTreeShowHidden=1
" /NERDTree

" Blockle plugin
" <leader>b to change block style from { … } to do … end

" Syntastic plugin
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list=1
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=1
let g:syntastic_check_on_wq=0
" /Syntastic

" vim-surround plugin
nmap <leader>c <Plug>CommentaryLine
nmap <leader>C <Plug>CommentaryLine
vmap <leader>c gc
vmap <leader>C gc
" /vim-surround

" vim-markdown plugin
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_fenced_languages = ['ruby', 'python', 'bash=sh', 'html']
" /vim-markdown

" ??  TODO: WTF?
let g:rct_completion_use_fri=0
command! -bar -nargs=1 OpenURL :!open <args>

" fzf.vim plugin
" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)
" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)
" /fzf.vim

" Ag plugin: Ack but better
if executable('ag')
  let g:ackprg = 'ag --vimgrep --smart-case'
endif
" /Ag

" Neomake plugin
call neomake#configure#automake('nrwi', 500)


" Commands
" ########

" Tidy
command! -range=% Tidy :<line1>,<line2>!tidy -quiet -indent -clean -bare -wrap 0 --show-errors 0 --show-body-only auto

" CDC = Change to Directory of Current file
command! CDC cd %:p:h

" Visual mode copy to pastebuffer
" kudos to Brad: http://xtargets.com/2010/10/13/cutting-and-pasting-source-code-from-vim-to-skype/
function! CopyWithLineNumbers() range
    redir @*
    sil echomsg "----------------------"
    sil echomsg expand("%")
    sil echomsg "----------------------"
    exec 'sil!' . a:firstline . ',' . a:lastline . '#'
    redir END
endfunction
command! -range CopyWithLineNumbers <line1>,<line2>call CopyWithLineNumbers()

" w!! to save with root permissions
cmap w!! w !sudo tee % > /dev/null

" TODO: WTF?
runtime macros/matchit.vim

" Cursorline gets broken by something above, so do it last
set cursorline
highlight CursorLine term=none cterm=none ctermbg=darkgrey guibg=#272727
highlight ColorColumn ctermbg=darkgrey guibg=#272727
" Highlight column 1 & 21 chars past textwidth
let &colorcolumn='+1,+'.join(range(21,80),',+')
